### ISSUE TITLE
希望提供预缓存功能

### ISSUE THREAD

**Issue by greensea** [marktony/PaperPlane#7]
在某些环境下，如地铁、地下室、郊外等地方，网络信号非常不好，这时候加载文章会变得非常困难。
希望能够在有无线网络的时候，自动预下载文章及图片，这样可以在没有网络或网络不好的情况下也能够流畅地阅读。

当然，后台自动下载可能会增加耗电量，这个功能也可以做成手动的。用于可以提前手动要求预下载所有内容，比如在出门前就可以使用家中的无线网络把最新的文章都下载回来，这样外出时到了网络不好的地方依旧能够流畅阅读。

最后感谢一下作者提供了这样一个整合知乎、果壳和豆瓣阅读的工具。

**Comment by marktony** [comment]
现在是有这个功能的，自动缓存的，设置里面有一个设置项，可以设置文章的保存时间，在这个时间内可以一直保存，如果希望一直保存，可以直接添加到收藏。😄

**Comment by greensea** [comment]
那真是太好了，我才刚刚开始使用，还没有注意到文章是会自动缓存的。

**Comment by marktony** [comment]
喜欢就好哟，那我把issue关了呀
