### ISSUE TITLE
项目未完成吧？

### ISSUE THREAD

**Issue by chenrongqi** [marktony/PaperPlane#8]
BookMarks  有明显的问题

**Comment by marktony** [comment]
能详细说明吗？

**Comment by chenrongqi** [comment]
bookMarks模块，点击searchActivity的返回按钮是无法返回的，还有这个地方容易死循环BookmarksPresenter 183行

**Comment by chenrongqi** [comment]
我看了你的detailActivity的actionBar和searchActivity，是因为activity共用了它的fragment中的关于menu的监听onOptionsItemSelected，你的searchActyvity没有这个

**Comment by marktony** [comment]
好的，感谢指出，已记录。
